ENTITY("commits"):
  NODE("Commit") commit:
    - hash = commits.hash
    - no_of_modifications = commits.no_of_modifications
    - commit_message = commits.commit_message
    - merge = commits.merge
    - date = DATETIME(commits.author_date, "%Y-%m-%d %H:%M:%S")

  RELATION(MATCH("Commit", hash=commits.parents), "CHILD", commit):

  NODE("Author") author:
    + id = commits.author_id

  RELATION(author, "AUTHORED", commit):

ENTITY("productivity"):
  # NODE("Commit") commit:
  #   + hash = productivity.commit_hash

  NODE("File") file:
    + path = productivity.new_path

  RELATION(MATCH("Commit", hash=productivity.commit_hash), "MODIFIED", file):
    - events = productivity.events
    - levenshtein_dist = productivity.levenshtein_dist
  