ENTITY("orders"):
  NODE("Order") order:
    + orderID = INT(orders.OrderID)
    - shipName = orders.ShipName
  NODE("Product") product:
    + productID = INT(products.ProductID)
  NODE("Employee") employee:
    + employeeID = INT(employees.EmployeeID)
  
  RELATION(order, "CONTAINS", product):
    - unitPrice = FLOAT(orders.UnitPrice)
    - quantity = FLOAT(orders.Quantity)

  RELATION(employee, "SOLD", order):


ENTITY("suppliers"):
  NODE("Supplier") supplier:
    + supplierID = INT(suppliers.SupplierID)
    - companyName = suppliers.CompanyName


ENTITY("products"):
  NODE("Product") product:
    + productID = INT(products.ProductID)
    - productName = products.ProductName
    - unitPrice = FLOAT(products.UnitPrice)

  NODE("Supplier") supplier:
    + supplierID = INT(suppliers.SupplierID)
  
  NODE("Category") category:
    + categoryID = INT(categories.CategoryID)

  RELATION(supplier, "SUPPLIES", product):
  
  RELATION(product, "PART_OF", category):

ENTITY("employees"):
  NODE("Employee") employee:
    + employeeID = INT(employees.EmployeeID)
    - firstName = employees.FirstName
    - lastName = employees.LastName
    - title = employees.Title

  RELATION(employee, "REPORTS_TO", MATCH("Employee", employeeID = INT(employees.ReportsTo))):

ENTITY("categories"):
  NODE("Category") category:
    + categoryID = INT(categories.CategoryID)
    - categoryName = categories.CategoryName
    - description = categories.Description
  
